/* SomnuMatrix — vocab-extra.js
   many more ways of saying the same thing. people don't dream in the app's
   words, they dream in their own: "the block of flats", "granny's place",
   "a lock-up", "a dirt track", "the woods". anything already understood keeps
   its meaning — these are only added where a word is going spare.
   loaded as a plain script; shares scope with the other files */
"use strict";

var EXTRA_VOCAB={
  somnucortower:["somnucor tower","the somnucor tower","the company tower","the tower at the middle of the city","somnucor's tower"],
  palace:["palace","palaces","the palace","royal palace","chateau","stately home","grand palace","summer palace"],
  manor:["manor","manors","manor house","mansion","mansions","great house","big house on the hill","country house"],
  /* the yard, the farm and the civic pieces: their own names back */
  cow:["cow","cows","cattle","a heifer","dairy cow","bullock","the cows in the field"],
  sheep:["sheep","a ewe","lamb","lambs","ram","flock of sheep"],
  pig:["pig","pigs","hog","sow","piglet"],
  goat:["goat","goats","nanny goat","billy goat"],
  chicken:["chicken","chickens","hen","hens","rooster","cockerel"],
  stag:["stag","deer","doe","hart","fawn","a deer in the trees"],
  owl:["owl","barn owl","tawny owl","an owl in the tree"],
  gull:["gull","gulls","seagull","seagulls"],
  crates:["crates","crate","packing cases","stack of crates","wooden boxes"],
  barrel:["barrel","barrels","cask","keg"],
  haybale:["hay bale","bale of hay","hay bales","round bale","straw bale"],
  silo:["silo","grain silo","feed silo"],
  farmhouse:["farmhouse","farm house","homestead","farmstead"],
  stable:["stable","stables","loose boxes","horse stable"],
  tractor:["tractor","farm tractor"],
  pond:["pond","duck pond","farm pond","a pond"],
  museum:["museum","the museum","art gallery","gallery of antiquities","hall of exhibits"],
  obelisk:["obelisk","a great obelisk","needle of stone"],
  shrine:["shrine","roadside shrine","wayside shrine","little shrine"],
  fishingboat:["fishing boat","trawler","smack"],
  /* ---- where people live and work ---- */
  house:["my house","our house","the old house","childhood home","family home","a home","semi","a place to live","the house i grew up in","my parents house","my parents' house","my childhood house","two-up two-down","a dwelling","the family place"],
  cottage:["bungalow","cabin","chalet","lodge","croft","hut","little house","small house","country cottage","log cabin","summer house","one-room house","wee house"],
  apartment:["flat","block of flats","apartment block","condo","studio flat","high-rise flats","bedsit","my flat","apartment building","walk-up","duplex"],
  tower:["turret","spire","belfry","keep","watchtower","bell tower","campanile","clock tower","round tower","tall tower","stone tower"],
  skyscraper:["office tower","glass tower","high rise","tower block","city tower","corporate tower","glass and steel tower"],
  hotel:["inn","guest house","boarding house","bed and breakfast","tavern with rooms","hostel","lodging house","the hotel lobby"],
  motel:["roadside motel","motor lodge","motor inn"],
  hospital:["clinic","infirmary","surgery","ward block","asylum","sanatorium","medical centre","medical center","emergency room","a&e"],
  school:["schoolhouse","classroom block","college","university building","academy","lecture hall","kindergarten","nursery school","my old school","primary school","high school building"],
  church:["basilica","abbey","priory","meeting house","kirk","chantry","sanctuary building","the old church","country church","white church"],
  cathedral:["minster","great cathedral","cathedral nave","duomo"],
  bank:["counting house","savings bank","bank branch","vault house","money house"],
  library:["reading room","book hall","archive","hall of books","records room","reading library"],
  station:["railway station","train station","platform building","terminus","depot","bus station","subway station","metro station","underground station","waiting room building"],
  courthouse:["court","court house","magistrates court","hall of justice","town hall","civic hall","assembly hall"],
  shop:["store","corner shop","bakery","butcher","grocer","boutique","chemist","pharmacy","newsagent","bookshop","record shop","dress shop","the shop on the corner","general store","cafe","coffee shop","diner","restaurant","bar","pub","teahouse","tea shop","pizzeria","takeaway"],
  warehouse:["depot building","storehouse","godown","goods shed","storage building","loading dock"],
  factory:["mill","foundry","refinery","assembly hall","industrial building","smokestack building"],
  barn:["byre","stables","cowshed","hayloft","granary","farm building","threshing barn"],
  shed:["lock-up","outhouse","potting shed","garden shed","tool shed","lean-to shed","workshop shed"],
  garage:["carport","car park building","auto shop","repair shop","mechanic's","chop shop"],
  ruin:["ruins","derelict building","abandoned building","wreck of a building","burnt-out building","shell of a house","crumbling walls","old ruin","gutted building"],
  tent:["canvas tent","camping tent","pavilion","marquee","circus tent","big top","camp"],
  bunker:["pillbox","blockhouse","dugout","concrete bunker","war bunker","command post"],
  statue:["effigy","figure of stone","carved figure","bronze figure","marble figure","memorial statue","a statue of someone"],
  monument:["memorial","cenotaph","war memorial","column","stone column","victory column","plinth"],
  tomb:["mausoleum","sepulchre","sepulcher","burial vault","family tomb","sarcophagus tomb","resting place"],
  lighthouse:["light tower","beacon tower","harbour light","the lighthouse beam"],
  windmill:["wind pump","old mill","mill with sails","water mill","mill house"],
  castle:["fortress","citadel","stronghold","fort","keep and walls"],
  crypt:["undercroft","burial chamber","charnel house","vault beneath","stone crypt"],
  hiddenroom:["secret room","hidden chamber","concealed room","room behind the wall","room that shouldn't be there","room i never knew about","priest hole"],
  mineshaft:["pit head","colliery","quarry workings","old mine"],
  altar:["shrine table","offering stone","stone altar","high altar","household shrine"],

  /* ---- ground, water, weather, growing things ---- */
  tree:["trees","an old tree","great tree","oak","elm","ash tree","beech","birch","willow","maple","sycamore","chestnut tree","apple tree","cherry tree","orchard tree","the woods","woodland","copse","grove","thicket of trees","treeline","forest"],
  pine:["fir","spruce","conifer","cedar","evergreen","pine trees","pine wood"],
  deadtree:["bare tree","leafless tree","blasted tree","withered tree","skeleton of a tree","dead trees","burnt tree"],
  palm:["palm trees","coconut palm","date palm","palms"],
  bush:["shrub","shrubbery","bushes","undergrowth","scrub","thicket","gorse","heather"],
  hedge:["hedgerow","privet","box hedge","garden hedge","hedges"],
  grass:["lawn","meadow","field","grassland","pasture","village green","paddock","playing field","clearing"],
  water:["river","stream","brook","creek","canal","lake","the sea","ocean","bay","lagoon","estuary","loch","fjord","reservoir","harbour","harbor","the water","flowing water","still water","the shore","shoreline","beach","waves"],
  hill:["knoll","hillside","slope","mound","ridge","hillock","downs","bank of earth","embankment"],
  mountain:["mountains","peak","summit","crag","alp","massif","mountainside","cliff","cliffs","escarpment","bluff","mountain range"],
  rock:["boulder","boulders","stone","stones","outcrop","rocks","rubble","scree","standing rock"],
  cave:["cavern","grotto","hollow in the rock","cave mouth","tunnel in the rock","underground cavern","the cave entrance"],
  flowers:["blossom","blooms","wildflowers","poppies","roses","daisies","lilies","tulips","lavender bushes","flower bed","garden flowers","a garden"],
  waterfall:["cascade","cataract","water falling","a fall of water"],
  volcano:["fire mountain","smoking mountain","caldera","erupting mountain"],
  crater:["impact crater","hollow in the ground","blast crater","pit in the ground"],
  graveyard:["cemetery","churchyard","burial ground","gravestones","headstones","the graves","necropolis","boneyard"],
  dune:["sand dunes","dunes of sand","rolling sand","sand hills","sand ridge"],
  oasis:["watering hole","green place in the desert","palms and water","desert spring"],
  giantmushroom:["huge mushroom","enormous toadstool","mushrooms as tall as trees","giant toadstool"],
  reeds:["rushes","bulrushes","marsh grass","reed bed","papyrus"],
  stormcloud:["thunderhead","black clouds","gathering storm","storm rolling in","dark clouds","the storm"],
  tornado:["twister","whirlwind","funnel cloud","cyclone"],
  flood:["floodwater","rising water","the water rose","deluge","inundation","flooding"],
  tidalwave:["tsunami","great wave","wall of water","rogue wave","the wave came"],
  wildfire:["forest fire","bushfire","the fire spread","burning forest","blaze in the trees"],
  blizzard:["snowstorm","whiteout","driving snow","snow storm"],
  sandstorm:["dust storm","haboob","wall of sand","sand in the air"],
  lavaflow:["molten rock","river of lava","magma","flowing lava"],
  fissure:["crack in the earth","chasm","rift in the ground","the ground split","crevasse","ravine","gorge"],
  sinkhole:["hole in the ground","the ground gave way","pit opened","collapsed ground"],
  meteor:["falling star","shooting star","fireball in the sky","meteorite","something falling from the sky"],

  /* ---- streets and the things along them ---- */
  road:["street","lane","avenue","boulevard","track","dirt track","path","pathway","footpath","alley","alleyway","highway","motorway","freeway","main street","high street","the road home","cobbled street","gravel road","country road","crossroads","junction","roundabout"],
  sidewalk:["pavement","footway","kerb","curb","paved walk"],
  bridge:["footbridge","overpass","viaduct","aqueduct","crossing over the water","stone bridge","rope bridge","covered bridge"],
  tunnel:["underpass","subway tunnel","culvert","passage under","tunnel mouth","the tunnel ahead"],
  stairs:["steps","stairway","staircase","flight of steps","stone steps","fire escape stairs"],
  gate:["gateway","gates","garden gate","iron gate","farm gate","turnstile","entrance gate"],
  fence:["fencing","picket fence","wooden fence","paling","railing","railings","post and rail"],
  chainlink:["wire fence","chain link fence","mesh fence","security fence"],
  stonewall:["dry stone wall","garden wall","old wall","brick wall","boundary wall","rampart"],
  fountain:["water feature","drinking fountain","town fountain","stone fountain","jet of water"],
  well:["wishing well","old well","water well","well head"],
  streetlight:["lamppost","lamp post","street lamp","gas lamp","the streetlights","a light on a pole"],
  trafficlight:["traffic lights","stop light"],
  sign:["signpost","street sign","road sign","shop sign","name plate","notice board"],
  billboard:["hoarding","advertising board","poster board","big sign"],
  bench:["park bench","wooden bench","benches"],
  pylon:["electricity pylon","power lines","transmission tower","telegraph pole","utility pole"],
  mailbox:["post box","letter box","mail box","pillar box"],
  trashcan:["bin","dustbin","rubbish bin","waste bin","garbage can","skip"],
  parking:["car park","parking lot","parking spaces","the car park"],
  playground:["swings","play park","climbing frame","see-saw","slide and swings","children's playground"],
  busstop:["bus shelter","stop for the bus","the bus stop"],
  marketstall:["market stalls","barrow","street market","bazaar stall","souk stall","fruit stall"],
  brazier:["fire basket","burning brazier","coal fire in a basket"],
  portal:["doorway to somewhere","way through","gateway of light","opening in the air","shimmering doorway","threshold"],
  rift:["tear in the air","tear in the world","split in reality","gash of light"],
  sigil:["symbol on the ground","drawn circle","painted symbol","magic circle","chalk circle","sign drawn in chalk"],
  wisps:["will o the wisps","floating lights","lights in the dark","witch lights","dancing lights","spirit lights","fireflies"],
  crystal:["gemstone","great crystal","quartz","geode","crystals growing","shard of crystal"],
  runestone:["carved stone","rune stone","inscribed stone","stone with writing","memorial stone"],
  cauldron:["great pot","witch's cauldron","cooking pot over a fire","iron pot"],
  throne:["seat of a king","great chair","seat of power","carved throne"],
  banner:["flag","pennant","heraldic banner","flags hanging"],
  scarecrow:["straw man","man of straw","figure in the field"],

  /* ---- things that move ---- */
  car:["motor car","saloon","sedan","hatchback","estate car","station wagon","taxi","cab","police car","old banger","my car","the family car","jeep","van"],
  truck:["lorry","pickup","pick-up truck","semi truck","articulated lorry","delivery truck","dump truck","fire engine","ambulance"],
  bus:["coach","double decker","school bus","minibus","the bus came"],
  train:["locomotive","steam train","freight train","carriages","the train pulled in","tram","streetcar","underground train","subway train"],
  boat:["rowing boat","dinghy","canoe","kayak","punt","raft","little boat","gondola"],
  ship:["vessel","liner","steamer","galleon","schooner","frigate","tanker","ferry","tall ship","sailing ship"],
  bicycle:["bike","pushbike","cycle","my bike","bicycles"],
  plane:["aeroplane","airplane","jet","airliner","biplane","helicopter","aircraft"],
  hotairballoon:["balloon in the sky","air balloon","basket under a balloon"],

  /* ---- people ---- */
  human:["figure","person","someone","somebody","a stranger","the stranger","a man","the man","a woman","the woman","people","folk","a passer-by","passerby","neighbour","neighbor","teacher","nurse","doctor","priest","soldier","guard","officer","driver","shopkeeper","baker","butcher","farmer","fisherman","sailor","beggar","musician","dancer","singer","painter","gardener","librarian","postman","cleaner","waiter","barman","old man","old woman","young man","young woman","my mother","my father","my sister","my brother","my friend","an old friend","my grandmother","my grandfather","my aunt","my uncle","my cousin","my wife","my husband","my partner","my teacher","my boss","a colleague","someone i knew","someone i used to know","a familiar face"],
  child:["kid","children","little girl","little boy","toddler","baby","infant","my son","my daughter","schoolchildren","a child i didn't know"],
  crowd:["throng","mob","gathering","congregation","queue","line of people","procession","audience","a crowd of people","press of bodies","market crowd"],
  shadow:["shadowy figure","dark figure","silhouette","shape in the dark","something in the corner","a shade","dark shape","figure with no face"],
  dog:["hound","puppy","stray dog","my dog","the neighbour's dog","wolfhound","collie","alsatian","terrier","barking dog"],
  cat:["kitten","tomcat","stray cat","my cat","black cat","tabby"],
  horse:["mare","stallion","pony","foal","colt","carthorse","racehorse","donkey","mule","ox","goat"],
  bird:["birds","sparrow","starling","swallow","magpie","pigeon","dove","gull","seagull","heron","swan","duck","goose","geese","robin","blackbird","kingfisher","eagle","hawk","falcon","parrot","flock of birds","birdsong"],
  creature:["thing","beast","animal","something alive","strange animal","unknown animal","something moving"],
  ghost:["spirit of someone","dead relative","the dead","shade of a person","someone who died","a haunting","presence in the room"],

  /* ---- other worlds and their furniture ---- */
  coral:["reef of coral","coral garden","brain coral","coral heads"],
  kelp:["kelp beds","weed forest","sea kelp","waving seaweed"],
  shipwreck:["broken hull","sunken wreck","hulk on the sea floor","ship on the bottom"],
  bonepile:["bone heap","scattered bones","boneyard pile"],
  spiritlanterns:["lanterns drifting","lights on the water","floating lights of the dead"],
  icespire:["ice pillar","frozen spire","pinnacle of ice","ice shard tower"],
  frozenlake:["ice sheet","frozen water","lake of ice","frozen surface"],
  cloudbank:["clouds below","bank of cloud","sea of cloud","cloud floor"],
  lightpillar:["column of light","shaft from heaven","beam from the sky","light coming down"],
  firepillar:["column of flame","tower of fire","pillar of flame"],
  emberfield:["glowing ground","field of embers","coals underfoot","burning ground"],
  voidshards:["broken pieces in the air","floating rubble","debris hanging","fragments in the dark"],
  starcrystal:["star fallen to earth","shard of starlight","glowing crystal from the sky"],
  moonrock:["grey rock of the moon","lunar rock","dust and craters"],
  alienflora:["plants unlike any i knew","luminous growths","strange growths","unearthly plants"],
  wreckedcar:["burnt out car","rusted wreck","car on its roof","stripped car","cars left to rot"],
  barricade:["makeshift barrier","piled defences","blockade","wall of junk"],
  scrapheap:["heap of metal","pile of wreckage","salvage pile","mountain of junk"],
  shanty:["tin shack","corrugated hut","shelter of scrap","hovel"],
  watertower:["tank on legs","water tank tower","rusted water tower"],
  falloutshelter:["blast shelter","shelter hatch","survival shelter"],
  dustbowl:["parched ground","cracked earth","dead ground","poisoned ground","barren plain"],

  /* ---- creatures ---- */
  fairy:["fae folk","little folk","flower fairy","winged folk","the fair ones"],
  elf:["elven folk","tall fair folk","elf lord","elf woman"],
  dwarf:["mountain folk","dwarf smith","bearded folk of the mountain"],
  goblin:["gremlin","imp-like creature","green goblin","goblin folk"],
  troll:["bridge troll","cave troll","great troll"],
  giant:["colossus","titan","giant man","giant woman","towering figure"],
  witch:["cunning woman","wise woman","old witch","village witch","woman who cursed me"],
  wizard:["old wizard","robed figure with a staff","spellcaster","conjuror","seer"],
  vampire:["blood drinker","the undead lord","creature that drank blood","one of the nosferatu"],
  werewolf:["wolf man","shape-shifter","man who became a wolf","beast that was a man"],
  zombie:["the risen dead","walking corpse","shambling dead","corpses walking"],
  skeleton:["bones walking","walking skeleton","animated bones"],
  ghostly:["apparition of a person"],
  angel:["winged figure of light","messenger of light","shining one","being of light"],
  demon:["hellish creature","infernal being","thing from below","horned creature"],
  mermaid:["woman of the sea","fish-tailed woman","sea maiden"],
  merman:["man of the sea","fish-tailed man","sea people"],
  dragon:["great wyrm","winged serpent","fire-breathing beast","dragon of old","scaled beast"],
  snake:["serpent in the grass","coiled snake","slithering thing","python-like snake"],
  spider:["web spinner","great spider","spiders everywhere","web and spider"],
  bats:["colony of bats","bats pouring out","flitting bats"],
  wolfpack:["pack of wolves"],
  unicorn:["horned horse","white horse with a horn"],
  kraken:["monster of the deep","many-armed monster","thing with tentacles"],
  whale:["great whale","leviathan of the sea","whale breaching"],
  phoenix:["bird of fire","burning bird","bird reborn from ash"],
  floatingeye:["watching eye","eye that followed me","great eye above"],

  /* ---- cultural ---- */
  torii:["gate of two posts","vermilion gate","shinto gate"],
  pagoda:["many-roofed tower","stepped tower with eaves"],
  mosque:["dome and minaret","house of prayer with a dome"],
  mandir:["carved stone temple","temple with a spire"],
  stupa:["dome shrine","white dome of stone"],
  yurt:["felt tent","round felt house","steppe tent"],
  pueblo:["adobe terraces","earth-walled village","mud houses stacked"],
  hacienda:["ranch house","estate house with arches"],
  riad:["house with an inner court","moroccan courtyard"],
  roundhouse:["thatched round house","round dwelling"],
  longhouse:["hall of timber","long timber hall"],
  cycladic:["white cube house","blue-domed house"],
  redlanterns:["lanterns strung above the street","row of red lanterns"],
  prayerflags:["flags strung between poles","coloured flags on a line"],
  papelpicado:["paper flags over the street","cut-paper bunting"],
  ofrenda:["table of remembrance","altar with photographs","candles and marigolds"],
  zengarden:["garden of sand and stone","raked gravel garden"],
  koipond:["pond with orange fish","fish pond with lilies"],
  bonsai:["dwarf tree in a pot","tiny tree in a dish"],
  tiledfountain:["fountain of blue tiles","patterned fountain"],
  marketawning:["awning over the stalls","striped canopy"],
  incenseburner:["smoking censer","bowl of incense"],
  windchimes:["chimes in the wind","bells that rang in the breeze"],
  maypole:["pole with ribbons","ribboned pole"],
  stringlights:["little lights strung overhead","lights across the street"],
  pergola:["walkway of vines","climbing plants over a frame"],
  monolith:["single great slab","standing slab of black stone"]
};

